// Generated by CoffeeScript 1.7.1

/*
ログインした後ユーザを待たせない様にするために、
  twitter.com/*を開いた時にもログインチェックを行うようにする
 */
chrome.extension.sendMessage({
  sendCode: 'checkLogin'
}, function(response) {
  LOGD('バッググランドへログインチェックを行うように命令しました。');
  LOGD(response);
});

//# sourceMappingURL=contentscript.map
