// Generated by CoffeeScript 1.3.3
var TwitterWeb;

TwitterWeb = (function() {

  function TwitterWeb(twitterHtml, ssl) {
    if (ssl == null) {
      ssl = true;
    }
    if (ssl === true) {
      this.scheme = 'https';
    } else {
      this.scheme = 'http';
    }
    this.login = this.isLogin(twitterHtml);
    this.authToken = this.getAuthToken(twitterHtml);
  }

  TwitterWeb.prototype.isLogin = function(html) {
    var div, passwordElementLength, usernameEmailElementLength;
    div = document.createElement('div');
    div.innerHTML = html;
    usernameEmailElementLength = document.evaluate('.//input[@id="username_or_email"]', div, null, XPathResult.UNORDERED_NODE_SNAPSHOT_TYPE, null).snapshotLength;
    passwordElementLength = document.evaluate('.//input[@id="password"]', div, null, XPathResult.UNORDERED_NODE_SNAPSHOT_TYPE, null).snapshotLength;
    LOGD("usernameEmailElementLength: " + usernameEmailElementLength);
    LOGD("passwordElementLength: " + passwordElementLength);
    LOGD(div);
    if (usernameEmailElementLength === 0 && passwordElementLength === 0) {
      return true;
    }
    return false;
  };

  TwitterWeb.prototype.getAuthToken = function(html) {
    var authToken, div;
    div = document.createElement('div');
    div.innerHTML = html;
    authToken = document.evaluate('.//input[@name="authenticity_token"]', div, null, XPathResult.ORDERED_NODE_SNAPSHOT_TYPE, null).snapshotItem(0).value;
    LOGD('authToken: ' + authToken);
    return authToken;
  };

  TwitterWeb.prototype.update = function(msg, successHandler, errorHandler) {
    var postApiUrl, prepareData;
    postApiUrl = this.scheme + '://twitter.com/status/update';
    prepareData = {
      authenticity_token: this.authToken,
      status: msg,
      include_entities: 'true',
      include_cards: '1'
    };
    LOGD(prepareData);
    return $.ajax(postApiUrl, {
      type: 'POST',
      dataType: 'json',
      data: prepareData,
      error: function(jqXHR, textStatus, errorThrown) {
        return errorHandler(jqXHR, textStatus, errorThrown);
      },
      success: function(data, textStatus, jqXHR) {
        return successHandler(data, textStatus, jqXHR);
      }
    });
  };

  return TwitterWeb;

})();
