// Generated by CoffeeScript 1.3.3
var AccessUrl, AppName, DEBUG, DefaultDelayAccessSecond, DefaultPostHeader, DefaultPostHeaderSplitter, DefaultReservedMsgLength, DefaultShowNotificationSecond, DefaultStatusUrlSplitter, DelayAccessSecondKey, MANIFEST, MaxMsgLength, PostHeaderKey, PostHeaderSplitterKey, ShowNotificationSecondKey, StatusUrlSplitterKey, TwitterLoginUrl;

DEBUG = true;

MANIFEST = chrome.app.getDetails();

AppName = MANIFEST.name;

MaxMsgLength = 140;

TwitterLoginUrl = 'https://twitter.com/login';

AccessUrl = 'http://twitter.com/intent/tweet';

DefaultReservedMsgLength = 20;

DefaultPostHeader = 'NowBrowsing';

DefaultPostHeaderSplitter = ': ';

DefaultStatusUrlSplitter = ' - ';

DefaultDelayAccessSecond = 60 * 1000;

DefaultShowNotificationSecond = 3 * 1000;

PostHeaderKey = 'postHeader';

PostHeaderSplitterKey = 'postHeaderSplitter';

DelayAccessSecondKey = 'delayAccessSecond';

StatusUrlSplitterKey = 'statusUrlSplitter';

DelayAccessSecondKey = 'delayAccessSecond';

ShowNotificationSecondKey = 'showNotificationSecond';
