// Generated by CoffeeScript 1.7.1
var AccessUrl, AppName, DEBUG, DefaultDelayAccessSecond, DefaultPostHeader, DefaultPostHeaderSplitter, DefaultShowNotificationSecond, DefaultStatusUrlSplitter, DelayAccessSecondKey, MANIFEST, MaxMsgLength, PostHeaderKey, PostHeaderSplitterKey, ReservedMsgLength, ShowNotificationSecondKey, StatusUrlSplitterKey, TwitterLoginUrl;

DEBUG = false;

MANIFEST = chrome.app.getDetails();

AppName = MANIFEST.name;

MaxMsgLength = 140;

TwitterLoginUrl = 'https://twitter.com/login';

AccessUrl = 'http://twitter.com/intent/tweet';

ReservedMsgLength = 20;

DefaultPostHeader = 'NowBrowsing';

DefaultPostHeaderSplitter = ': ';

DefaultStatusUrlSplitter = ' - ';

DefaultDelayAccessSecond = 60 * 1000;

DefaultShowNotificationSecond = 3 * 1000;

PostHeaderKey = 'postHeader';

PostHeaderSplitterKey = 'postHeaderSplitter';

DelayAccessSecondKey = 'delayAccessSecond';

StatusUrlSplitterKey = 'statusUrlSplitter';

DelayAccessSecondKey = 'delayAccessSecond';

ShowNotificationSecondKey = 'showNotificationSecond';
