// Generated by CoffeeScript 1.7.1

/*
@author PyYoshi
 */

/*
デバッグメッセージ表示用

@param msg {String} DEBUGが true: メッセージを表示 false: メッセージは表示されない
 */
var LOGD, genStatusMsg, getLocalStorage, setLocalStorage;

LOGD = function(msg) {
  if (msg == null) {
    msg = null;
  }
  if (DEBUG === true) {
    return console.log(msg);
  }
};


/*
文字制限に合わせてページタイトルを整形し投稿用メッセージとして返す関数

@param postHeader {String} ポストヘッダー
@param postHeaderSplitter {String} ポストヘッダーとページタイトルを分ける文字列
@param title {String} タイトル
@param statusUrlSplitter {String} ページタイトルとURLを分ける文字列
@return {String} 整形済み投稿用メッセージ
 */

genStatusMsg = function(postHeader, postHeaderSplitter, title, statusUrlSplitter) {
  var maxTitleLength, threeDots;
  if (postHeader == null) {
    postHeader = null;
  }
  if (postHeaderSplitter == null) {
    postHeaderSplitter = null;
  }
  if (title == null) {
    title = null;
  }
  if (statusUrlSplitter == null) {
    statusUrlSplitter = null;
  }
  threeDots = '...';
  maxTitleLength = MaxMsgLength - (postHeader.length + postHeaderSplitter.length + statusUrlSplitter.length + ReservedMsgLength);
  if (title.length > maxTitleLength) {
    return postHeader + postHeaderSplitter + title.slice(0, maxTitleLength - threeDots.length) + threeDots + statusUrlSplitter;
  } else {
    return postHeader + postHeaderSplitter + title + statusUrlSplitter;
  }
};


/*
localStorageから値を取得する関数

@param targetKey {String} localStorageのkey
@param defaultValue {String||Number} デフォルト値
preturn {String||Number} localStorageから取得した値
 */

getLocalStorage = function(targetKey, defaultValue) {
  if (defaultValue == null) {
    defaultValue = null;
  }
  if (targetKey === '' || typeof targetKey === 'undefined' || targetKey === null) {
    return null;
  }
  if (typeof localStorage["" + targetKey] === 'undefined' || localStorage["" + targetKey] === null) {
    return defaultValue;
  } else {
    return localStorage["" + targetKey];
  }
};


/*
localStorageへ値をセットする関数

@param targetKey {String} localStorageのkey
@param value {String||Number}
@return {Boolean} true: セットできた false: セット出来なかった
 */

setLocalStorage = function(targetKey, value) {
  var error;
  if (value == null) {
    value = null;
  }
  if (targetKey === '' || typeof targetKey === 'undefined' || targetKey === null) {
    return false;
  }
  if (typeof value === 'undefined') {
    return false;
  }
  try {
    localStorage["" + targetKey] = value;
    return true;
  } catch (_error) {
    error = _error;
    LOGD('=== localStorageへ値を正常にセットできませんでした ===');
    LOGD(error);
    LOGD('======================================================');
    return false;
  }
};

//# sourceMappingURL=util.map
