// Generated by CoffeeScript 1.3.3
/*
@author PyYoshi
*/

/*
デバッグメッセージ表示用

@param msg {String} DEBUGが true: メッセージを表示 false: メッセージは表示されない
*/

var LOGD, cleanPageTitle, getLocalStorage, setLocalStorage;

LOGD = function(msg) {
  if (msg == null) {
    msg = null;
  }
  if (DEBUG === true) {
    return console.log(msg);
  }
};

/*
文字制限に合わせてページタイトルを整形する関数

@param title {String} タイトル
@param postHeaderLength {Number} ポストヘッダーの文字数
@return {String} 整形済みタイトル
*/


cleanPageTitle = function(title, postHeaderLength) {
  var maxTitleLength, threeDots;
  if (title == null) {
    title = null;
  }
  if (postHeaderLength == null) {
    postHeaderLength = 0;
  }
  threeDots = '...';
  maxTitleLength = MaxMsgLength - (ReservedMsgLength + threeDots.length + PostHeaderSpliter.length + postHeaderLength);
  if (title.length > maxTitleLength) {
    title = title.slice(0, maxTitleLength) + threeDots;
  }
  return title;
};

/*
localStorageから値を取得する関数

@param targetKey {String} localStorageのkey
@param defaultValue {String||Number} デフォルト値
preturn {String||Number} localStorageから取得した値
*/


getLocalStorage = function(targetKey, defaultValue) {
  if (defaultValue == null) {
    defaultValue = null;
  }
  if (targetKey === '' || typeof targetKey === 'undefined' || targetKey === null) {
    return null;
  }
  if (typeof localStorage["" + targetKey] === 'undefined' || localStorage["" + targetKey] === null) {
    return defaultValue;
  } else {
    return localStorage["" + targetKey];
  }
};

/*
localStorageへ値をセットする関数

@param targetKey {String} localStorageのkey
@param value {String||Number}
@return {Boolean} true: セットできた false: セット出来なかった
*/


setLocalStorage = function(targetKey, value) {
  if (value == null) {
    value = null;
  }
  if (targetKey === '' || typeof targetKey === 'undefined' || targetKey === null) {
    return false;
  }
  if (value === '' || typeof value === 'undefined') {
    return false;
  }
  try {
    localStorage["" + targetkey] = value;
    return true;
  } catch (error) {
    LOGD('=== localStorageへ値を正常にセットできませんでした ===');
    LOGD(error);
    LOGD('======================================================');
    return false;
  }
};
